### ISSUE TITLE
Add Nokogiri to Gemspec?

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/traject_plus#5]
Realized that I cannot use the `traject_plus` gem (at least the `XmlReader`) without installing Nokogiri (it's used by that Reader class). Should Nokogiri be added to the gemspec file? Happy to open a new PR for that, uncertain of Ruby protocol for embedded required libraries like this though.

**Comment by jcoyne** [comment]
Nokogiri is a dependency of Traject, so we don't need to make it a dependency of traject_plus.
