### ISSUE TITLE
add multiple fields (not multiple values in an array) to a `compose` output?

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/traject_plus#9]
Figuring out how to add multiple fields to a `compose` output.

Mapping config has this:
```ruby
compose 'test', ->(record, accumulator, _context) { accumulator << record } do
  require_relative './lib/traject_plus/macros/xml'
  extend TrajectPlus::Macros::Xml
  to_field 'composed', extract_xml("/TEI/teiHeader/encodingDesc/projectDesc/p", ns)
  to_field 'id_elbing', extract_xml("/TEI/text/body/msDesc/msIdentifier/altIdentifier[@type='Elbing']/idno", ns)
end
```

This outputs (in DebugWriter): 

```
record_num_1 test                      {"composed"=>["appropriate test value"]}
```

**Comment by cbeer** [comment]
This should work, maybe `id_elbing` isn't picking up anything?

**Comment by cmharlow** [comment]
It picks it up as a non-compose config line just below it.

**Comment by cmharlow** [comment]
let me test another value.

**Comment by cbeer** [comment]
Ok; here's a test that shows it working: https://github.com/sul-dlss/traject_plus/pull/10

**Comment by cmharlow** [comment]
proven to be local config issues, i'll need to explore further, but will close this issue.
